#!/usr/bin/tclsh

#| Create a script to load files for the package.

set directory [lindex $argv 0]
set package_name [lindex $argv 1]
set version [lindex $argv 2]

if { $argc != 3 || ![regexp {[0-9]+\.[0-9]+\.[0-9]+} $version] } {
    error "Usage: pkg_mkIndex directory package_name version"
}

package require fileutil
set tcl_directory [file join [pwd] $directory]
set tcl_files [fileutil::findByPattern $tcl_directory *.tcl]
set script "package ifneeded $package_name $version "

foreach tcl_file $tcl_files {
    set file_path_relative [fileutil::stripPath $tcl_directory $tcl_file]
    append script [string map \
                          [list {$file_path_relative} $file_path_relative] \
                          {[list source [file join $dir $file_path_relative]]\n}]
}


fileutil::writeFile [file join $tcl_directory pkgIndex.tcl] $script
