name: 'Create Deploy Markdown'
inputs:
  version:
    description: 'Version'
    required: true
    type: string
  release:
    description: 'Release'
    required: true
    type: string
  repo_name:
    description: 'Repository Name'
    required: true
    type: string
  notes_file:
    description: "Notes file"
    required: true
    type: string

runs:
  using: "composite"    
  steps:
    - name: Deploy Markdown file
      run: |
          cat << "EOF" >> ${{ inputs.notes_file }}
          #### Install:
          ```
          sudo dpkg -i ${{ inputs.repo_name }}_${{ inputs.version }}-${{ inputs.release }}_all.deb
          ```
          EOF
          
      shell: bash
