# Run all tests

name: tcl

on:
  push:
    branches:
      - temp_test

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Dependencies
        run: |
          sudo cat <<EOF >/etc/apt/sources.list.d/qcode.list
          deb http://deb.qcode.co.uk stretch main
          EOF
          sudo apt-get update && sudo apt-get -y install tcllib tdom

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests for all exercises
        run: |
          cd test
          tclsh all.tcl
