name: 'Pull Request Linting'

on:
  pull_request:
    paths:
      - '**.tcl'

jobs:
  linting:
    name: Linting
    uses: qcode-software/ci-development/.github/workflows/qcode-ci.yml@v1.0.0
    with:
      files: |
        tcl/**.tcl
      max_line_length: 100
      check_line_lengths: true
      check_proc_names: true
    secrets: inherit
