name: 'Pull Request Linting'

on:
  pull_request:
    paths:
      - '**.tcl'

jobs:
  linting:
    name: Linting
    uses: qcode-software/ci-development/.github/workflows/qcode-ci.yml@v2.0.0
    with:
      files: |
        tcl/**.tcl
      tcl_directory: tcl
      test_directory: test
      max_line_length: 100
      max_file_length: 400
      max_proc_body_length: 80
      check_line_lengths: true
      check_proc_names: true
      check_procs_have_unit_tests: true
      check_file_lengths: true
      check_proc_lengths: true
      check_proc_comments: true
    secrets: inherit
