name: "Tag and Release"

on:
  push:
    branches:
      - master

jobs:
  release:
    name: "release"
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      RELEASE: 0
      MAINTAINER: hackers@qcode.co.uk
      MODULE_NAME: qcode
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Semantic Version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}"
          search_commit_body: true
      - name: Create Tcl Module
        uses: ./actions/tcl-module-build
        with:
          source_directory: tcl
          version: ${{ steps.version.outputs.version }}
          package: ${{ env.MODULE_NAME }}
          tcl_module_file: ${{ env.MODULE_NAME }}-${{ steps.version.outputs.version }}.tm
      - name: Create Archive
        uses: ./actions/tcl-module-archive
        with:
          version: ${{ steps.version.outputs.version }}
          repo_name: ${{ env.REPO_NAME }}
          archive_file: ${{ env.REPO_NAME }}-${{ steps.version.outputs.version }}.tar.gz
          tcl_module_file: ${{ env.MODULE_NAME }}-${{ steps.version.outputs.version }}.tm
      - name: Create Debian Package
        uses: ./actions/tcl-module-debian-package
        with:
          version: ${{ steps.version.outputs.version }}
          repo_name: ${{ env.REPO_NAME }}
          maintainer: ${{ env.MAINTAINER }}
          release: ${{ env.RELEASE }}
          debian_package_file: ${{ env.REPO_NAME }}_${{ steps.version.outputs.version }}-${{ env.RELEASE }}_all.deb
          debian_package_description: "Description: QCode Tcl Debian Package"
          depends: "tcl,tcllib,html2text,curl,tclcurl"
          tcl_module_file: ${{ env.MODULE_NAME }}-${{ steps.version.outputs.version }}.tm
      - name: Create release
        uses: ./actions/tcl-module-release
        with:
          tag: v${{ steps.version.outputs.version }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          archive_file: ${{ env.REPO_NAME }}-${{ steps.version.outputs.version }}.tar.gz
          debian_package_file: ${{ env.REPO_NAME }}_${{ steps.version.outputs.version }}-${{ env.RELEASE }}_all.deb
      - name: Upload Debian Package
        uses: ./actions/tcl-module-debian-package-upload
        with:
          private_key: ${{ secrets.DEB_PRIVATE_KEY }}
          repo_name: ${{ env.REPO_NAME }}
          debian_package_file: ${{ env.REPO_NAME }}_${{ steps.version.outputs.version }}-${{ env.RELEASE }}_all.deb
          remote_user: deb
          remote_host: ssh.debian.qcode.co.uk
          remote_dir: debian.qcode.co.uk